import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#1d1d1d]">
        <main className="max-w-6xl mx-auto">
          <div>
            <h3>
              <Link href={"/"}>Home</Link>
            </h3>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
